

export const ShuHan = [
  { img: "img_07", mingzi: "劉備 (玄德)", name: "Liu Bei (Xuande)" },
  { img: "img_08", mingzi: "關羽 (雲長)", name: "Guan Yu (Yunchang)" },
  { img: "img_09", mingzi: "張飛 (益德)", name: "Zhang Fei (Yide)" },
  { img: "img_10", mingzi: "趙雲 (子龍)", name: "Zhao Yun (Zilong)" },
  { img: "img_10", mingzi: "諸葛亮 (孔明)", name: "Zhuge Liang (Kongming)" },
  { img: "img_10", mingzi: "馬超 (孟起)", name: "Ma Chao (Mengqi)" },
  { img: "img_10", mingzi: "黃忠 (漢升)", name: "Huang Zhong (Hansheng)" },
  { img: "img_10", mingzi: "姜維 (伯約)", name: "Jiang Wei (Boyue)" },
  { img: "img_10", mingzi: "關平", name: "Guan Ping" },
  { img: "img_10", mingzi: "馬岱", name: "Ma Dai" },
  { img: "img_10", mingzi: "李嚴 (正方)", name: "Li Yan (Zhengping)" },
  { img: "img_10", mingzi: "關興 (安國)", name: "Guan Xing (Anguo)" },
  { img: "img_10", mingzi: "馬謖 (幼常)", name: "Ma Su (Youchang)" },
  { img: "img_10", mingzi: "馬良 (季常)", name: "Ma Liang (Jichang)" },
  { img: "img_10", mingzi: "劉協 (伯和)", name: "Liu Xie (Bohe)" },
  { img: "img_10", mingzi: "劉禪 (公嗣)", name: "Liu Shan (Gongsi)" },
  { img: "img_12", mingzi: "曹節", name: "Cao Jie" },
  { img: "img_10", mingzi: "劉表 (景升)", name: "Liu Biao (Jingsheng)" },
  { img: "img_10", mingzi: "陶謙 (恭祖)", name: "Tao Qian (Gongzu)" },
  { img: "img_10", mingzi: "曹豹", name: "Cao Bao" },
  { img: "img_10", mingzi: "董承", name: "Dong Cheng" },
  { img: "img_10", mingzi: "法正 (孝直)", name: "Fa Zheng (Xiaozhi)" },
  { img: "img_10", mingzi: "甘夫人", name: "Lady Gan" },
  { img: "img_10", mingzi: "吉本", name: "Ji Ping" },
  { img: "img_10", mingzi: "劉琮", name: "Liu Cong" },
  { img: "img_10", mingzi: "劉度", name: "Liu Du" },
  { img: "img_10", mingzi: "劉琦", name: "Liu Qi" },
  { img: "img_10", mingzi: "劉璋 (季玉)", name: "Liu Zhang (Jiyu)" },
];

export const Wei = [
  { img: "img_12", mingzi: "曹操 (孟德)", name: "Cao Cao (Mengde)" },
  { img: "img_12", mingzi: "曹丕 (子桓)", name: "Cao Pi (Zihuan)" },
  { img: "img_12", mingzi: "曹彰 (子文)", name: "Cao Zhang (Ziwen)" },
  { img: "img_12", mingzi: "曹植 (子建)", name: "Cao Zhi (Zijian)" },
  { img: "img_12", mingzi: "曹沖 (倉舒)", name: "Cao Chong (Cangshu)" },
  { img: "img_12", mingzi: "司馬懿 (仲達)", name: "Sima Yi (Zhongda)" },
  { img: "img_12", mingzi: "曹叡 (元仲)", name: "Cao Rui (Yuanzhong)" },
  { img: "img_12", mingzi: "曹芳 (蘭卿)", name: "Cao Fang (Lanqing)" },
  { img: "img_12", mingzi: "許褚 (仲康)", name: "Xu Chu (Zhongkang)" },
  { img: "img_12", mingzi: "曹洪 (子廉)", name: "Cao Hong (Zilian)" },
  { img: "img_12", mingzi: "曹仁 (子孝)", name: "Cao Ren (Zixiao)" },
  { img: "img_12", mingzi: "郝昭 (伯道)", name: "Hao Zhao (Bodao)" },
  { img: "img_12", mingzi: "李典 (曼成)", name: "Li Dian (Mancheng)" },
  { img: "img_12", mingzi: "曹真 (子丹)", name: "Cao Zhen (Zidan)" },
  { img: "img_12", mingzi: "曹爽 (昭伯)", name: "Cao Shuang (Zhaobo)" },
  { img: "img_12", mingzi: "蔡瑁 (德珪)", name: "Cai Mao (Degui)" },
  { img: "img_12", mingzi: "陳登 (元龍)", name: "Chen Deng (Yuanlong)" },
  { img: "img_12", mingzi: "陳珪 (漢瑜)", name: "Chen Gui (Hanyu)" },
  { img: "img_12", mingzi: "陳群 (長文)", name: "Chen Qun (Changwen)" },
  { img: "img_12", mingzi: "程昱 (仲徳)", name: "Cheng Yu (Zhongde)" },
  { img: "img_12", mingzi: "董昭 (公仁)", name: "Dong Zhao (Gongren)" },
  { img: "img_12", mingzi: "郭淮 (伯濟)", name: "Guo Huai (Boji)" },
  { img: "img_12", mingzi: "郭嘉 (奉孝)", name: "Guo Jia (Fengxiao)" },
  { img: "img_12", mingzi: "華歆 (子魚)", name: "Han Xin (Ziyu)" },
  { img: "img_12", mingzi: "黃權 (公衡)", name: "Huang Quan (Gongheng)" },
  { img: "img_12", mingzi: "韓玄", name: "Han Xuan" },
  { img: "img_12", mingzi: "蔣幹", name: "Jiang Gan" },
  { img: "img_12", mingzi: "李豐 (安國)", name: "Li Feng (Anguo)" },
  { img: "img_12", mingzi: "劉岱 (公山)", name: "Liu Dai (Gongshan)" },
  { img: "img_12", mingzi: "呂伯奢", name: "Lü Boshe" },
  { img: "img_12", mingzi: "郭皇后", name: "Empress Guo" },
];

export const Wu = [
  { img: "img_07", mingzi: "孫堅 (文臺)", name: "Sun Jian (Wentai)" },
  { img: "img_07", mingzi: "孫策 (伯符)", name: "Sun Ce (Bofu)" },
  { img: "img_07", mingzi: "孫權 (仲謀)", name: "Sun Quan (Zhongmou)" },
  { img: "img_07", mingzi: "周瑜 (公瑾)", name: "Zhou Yu (Gongjin)" },
  { img: "img_07", mingzi: "魯肅 (子敬)", name: "Lu Su (Zijing)" },
  { img: "img_07", mingzi: "陸遜 (伯言)", name: "Lu Xun (Boyan)" },
  { img: "img_07", mingzi: "程普 (德謀)", name: "Cheng Pu (Demou)" },
  { img: "img_07", mingzi: "甘寧 (興霸)", name: "Gan Ning (Xingba)" },
  { img: "img_07", mingzi: "黃蓋 (公覆)", name: "Huang Gai (Gongfu)" },
  { img: "img_07", mingzi: "呂蒙 (子明)", name: "Lü Meng (Ziming)" },
  { img: "img_07", mingzi: "韓當 (義公)", name: "Han Dang (Yigong)" },
  { img: "img_07", mingzi: "丁奉 (承淵)", name: "Ding Feng (Chengyuan)" },
  { img: "img_07", mingzi: "孫夫人", name: "Lady Sun" },
  { img: "img_07", mingzi: "大橋", name: "Da Qiao" },
  { img: "img_07", mingzi: "小橋", name: "Xiao Qiao" },
  { img: "img_07", mingzi: "陸績 (公紀)", name: "Lu Ji (Gongji)" },
];

export const Other = [
  { img: "img_12", mingzi: "董卓 (仲穎)", name: "Dong Zhuo (Zhongying)" },
  { img: "img_12", mingzi: "呂布 (奉先)", name: "Lu Bu (Fengxian)" },
  { img: "img_12", mingzi: "貂蟬", name: "Diao Chan" },
  { img: "img_12", mingzi: "郭汜", name: "Guo Si" },
  { img: "img_12", mingzi: "華雄", name: "Hua Xiong" },
  { img: "img_12", mingzi: "李傕 (稚然)", name: "Li Jue (Zhiran)" },
  { img: "img_12", mingzi: "李儒 (文優)", name: "Li Ru (Wenyou)" },
  { img: "img_12", mingzi: "陳宮 (公臺)", name: "Chen Gong (Gongtai)" },
  { img: "img_12", mingzi: "公孫瓚 (伯珪)", name: "Gongsun Zan (Bogui)" },
  { img: "img_12", mingzi: "郭圖", name: "Guo Tu" },
  { img: "img_12", mingzi: "韓遂 (文約)", name: "Han Sui (Wenyue)" },
  { img: "img_12", mingzi: "華佗 (元化)", name: "Hua Tuo (Yuanhua)" },
  { img: "img_12", mingzi: "紀靈", name: "Ji Ling" },
  { img: "img_12", mingzi: "馬騰 (壽成)", name: "Ma Teng (Shoucheng)" },
];