

export const ShuHan = [
  { img: "img_07", mingzi: "劉備 (玄德)", name: "Liu Bei (Xuande)" },
  { img: "img_08", mingzi: "關羽 (雲長)", name: "Guan Yu (Yunchang)" },
  { img: "img_09", mingzi: "張飛 (益德)", name: "Zhang Fei (Yide)" },
  { img: "img_10", mingzi: "趙雲 (子龍)", name: "Zhao Yun (Zilong)" },
  { img: "img_10", mingzi: "諸葛亮 (孔明)", name: "Zhuge Liang (Kongming)" },
  { img: "img_10", mingzi: "馬超 (孟起)", name: "Ma Chao (Mengqi)" },
  { img: "img_10", mingzi: "黃忠 (漢升)", name: "Huang Zhong (Hansheng)" },
  { img: "img_10", mingzi: "龐統 (士元)", name: "Pang Tong (Shiyuan)" },
  { img: "img_10", mingzi: "姜維 (伯約)", name: "Jiang Wei (Boyue)" },
  { img: "img_10", mingzi: "關平", name: "Guan Ping" },
  { img: "img_10", mingzi: "馬岱", name: "Ma Dai" },
  { img: "img_10", mingzi: "李嚴 (正方)", name: "Li Yan (Zhengping)" },
  { img: "img_10", mingzi: "關興 (安國)", name: "Guan Xing (Anguo)" },
  { img: "img_10", mingzi: "王平 (子均)", name: "Wang Ping (Zijun)" },
  { img: "img_10", mingzi: "魏延 (文長)", name: "Wei Yan (Wenchang)" },
  { img: "img_10", mingzi: "張苞", name: "Zhang Bao" },
  { img: "img_10", mingzi: "馬謖 (幼常)", name: "Ma Su (Youchang)" },
  { img: "img_10", mingzi: "馬良 (季常)", name: "Ma Liang (Jichang)" },
  { img: "img_10", mingzi: "劉協 (伯和)", name: "Liu Xie (Bohe)" },
  { img: "img_10", mingzi: "劉禪 (公嗣)", name: "Liu Shan (Gongsi)" },
  { img: "img_10", mingzi: "麋芳 (子方)", name: "Mi Fang (Zifang)" },
  { img: "img_10", mingzi: "孫乾 (公祐)", name: "Sun Qian (Gongyou)" },
  { img: "img_12", mingzi: "曹節", name: "Cao Jie" },
  { img: "img_10", mingzi: "徐庶 (元直)", name: "Xu Shu (Yuanzhi)" },
  { img: "img_10", mingzi: "劉表 (景升)", name: "Liu Biao (Jingsheng)" },
  { img: "img_10", mingzi: "陶謙 (恭祖)", name: "Tao Qian (Gongzu)" },
  { img: "img_10", mingzi: "曹豹", name: "Cao Bao" },
  { img: "img_10", mingzi: "董承", name: "Dong Cheng" },
  { img: "img_10", mingzi: "法正 (孝直)", name: "Fa Zheng (Xiaozhi)" },
  { img: "img_10", mingzi: "甘夫人", name: "Lady Gan" },
  { img: "img_10", mingzi: "吉本", name: "Ji Ping" },
  { img: "img_10", mingzi: "劉琮", name: "Liu Cong" },
  { img: "img_10", mingzi: "劉度", name: "Liu Du" },
  { img: "img_10", mingzi: "劉琦", name: "Liu Qi" },
  { img: "img_10", mingzi: "劉璋 (季玉)", name: "Liu Zhang (Jiyu)" },
  { img: "img_10", mingzi: "麋夫人", name: "Lady Mi" },
  { img: "img_10", mingzi: "王允 (子师)", name: "Wang Yun (Zishi)" },
  { img: "img_10", mingzi: "嚴顏", name: "Yan Yan" },
  { img: "img_10", mingzi: "楊儀 (威公)", name: "Yang Yi (Weigong)" },
  { img: "img_10", mingzi: "張松 (子喬)", name: "Zhang Song (Ziqiao)" },
  { img: "img_10", mingzi: "張翼 (伯恭)", name: "Zhang Yi (Bogong)" },
  { img: "img_10", mingzi: "趙範", name: "Zhao Fan" },
  { img: "img_10", mingzi: "周倉", name: "Zhou Cang" },
];

export const Wei = [
  { img: "img_12", mingzi: "曹操 (孟德)", name: "Cao Cao (Mengde)" },
  { img: "img_12", mingzi: "曹丕 (子桓)", name: "Cao Pi (Zihuan)" },
  { img: "img_12", mingzi: "曹彰 (子文)", name: "Cao Zhang (Ziwen)" },
  { img: "img_12", mingzi: "曹植 (子建)", name: "Cao Zhi (Zijian)" },
  { img: "img_12", mingzi: "曹沖 (倉舒)", name: "Cao Chong (Cangshu)" },
  { img: "img_12", mingzi: "司馬懿 (仲達)", name: "Sima Yi (Zhongda)" },
  { img: "img_12", mingzi: "荀彧 (文若)", name: "Xun Yu (Wenruo)" },
  { img: "img_12", mingzi: "曹叡 (元仲)", name: "Cao Rui (Yuanzhong)" },
  { img: "img_12", mingzi: "曹芳 (蘭卿)", name: "Cao Fang (Lanqing)" },
  { img: "img_12", mingzi: "夏侯淵 (妙才)", name: "Xiahou Yuan (Miaocai)" },
  { img: "img_12", mingzi: "許褚 (仲康)", name: "Xu Chu (Zhongkang)" },
  { img: "img_12", mingzi: "徐晃 (公明)", name: "Xu Huang (Gongming)" },
  { img: "img_12", mingzi: "夏侯惇 (元讓)", name: "Xiahou Dun (Yuanrang)" },
  { img: "img_12", mingzi: "曹洪 (子廉)", name: "Cao Hong (Zilian)" },
  { img: "img_12", mingzi: "張遼 (文遠)", name: "Zhang Liao (Wenyuan)" },
  { img: "img_12", mingzi: "曹仁 (子孝)", name: "Cao Ren (Zixiao)" },
  { img: "img_12", mingzi: "于禁 (文則)", name: "Yu Jin (Wenze)" },
  { img: "img_12", mingzi: "張郃 (儁乂)", name: "Zhang He (Junyi)" },
  { img: "img_12", mingzi: "夏侯霸 (仲權)", name: "Xiahou Ba (Zhongquan)" },
  { img: "img_12", mingzi: "郝昭 (伯道)", name: "Hao Zhao (Bodao)" },
  { img: "img_12", mingzi: "李典 (曼成)", name: "Li Dian (Mancheng)" },
  { img: "img_12", mingzi: "司馬昭 (子上)", name: "Sima Zhao (Zishang)" },
  { img: "img_12", mingzi: "龐德 (令明)", name: "Pang De (Lingming)" },
  { img: "img_12", mingzi: "秦朗 (元明)", name: "Qin Lang (Yuanming)" },
  { img: "img_12", mingzi: "牛金", name: "Niu Jin" },
  { img: "img_12", mingzi: "曹真 (子丹)", name: "Cao Zhen (Zidan)" },
  { img: "img_12", mingzi: "曹爽 (昭伯)", name: "Cao Shuang (Zhaobo)" },
  { img: "img_12", mingzi: "蔡瑁 (德珪)", name: "Cai Mao (Degui)" },
  { img: "img_12", mingzi: "孫禮 (德達)", name: "Sun Li (Deda)" },
  { img: "img_12", mingzi: "吳質 (季重)", name: "Wu Zhi (Jizhong)" },
  { img: "img_12", mingzi: "司馬師 (子元)", name: "Sima Shi (Ziyuan)" },
  { img: "img_12", mingzi: "陳登 (元龍)", name: "Chen Deng (Yuanlong)" },
  { img: "img_12", mingzi: "陳珪 (漢瑜)", name: "Chen Gui (Hanyu)" },
  { img: "img_12", mingzi: "陳群 (長文)", name: "Chen Qun (Changwen)" },
  { img: "img_12", mingzi: "程昱 (仲徳)", name: "Cheng Yu (Zhongde)" },
  { img: "img_12", mingzi: "董昭 (公仁)", name: "Dong Zhao (Gongren)" },
  { img: "img_12", mingzi: "郭淮 (伯濟)", name: "Guo Huai (Boji)" },
  { img: "img_12", mingzi: "郭嘉 (奉孝)", name: "Guo Jia (Fengxiao)" },
  { img: "img_12", mingzi: "華歆 (子魚)", name: "Han Xin (Ziyu)" },
  { img: "img_12", mingzi: "黃權 (公衡)", name: "Huang Quan (Gongheng)" },
  { img: "img_12", mingzi: "韓玄", name: "Han Xuan" },
  { img: "img_12", mingzi: "蔣幹", name: "Jiang Gan" },
  { img: "img_12", mingzi: "李豐 (安國)", name: "Li Feng (Anguo)" },
  { img: "img_12", mingzi: "劉岱 (公山)", name: "Liu Dai (Gongshan)" },
  { img: "img_12", mingzi: "呂伯奢", name: "Lü Boshe" },
  { img: "img_12", mingzi: "王朗 (景興)", name: "Wang Lang (Jingxing)" },
  { img: "img_12", mingzi: "郭皇后", name: "Empress Guo" },
  { img: "img_12", mingzi: "楊修 (德祖)", name: "Yang Xiu (Dezu)" },
  { img: "img_12", mingzi: "張魯 (公祺)", name: "Zhang Lu (Gongqi)" },
  { img: "img_12", mingzi: "鍾繇 (元常)", name: "Zhong Yao (Yuanchang)" },
];

export const Wu = [
  { img: "img_07", mingzi: "孫堅 (文臺)", name: "Sun Jian (Wentai)" },
  { img: "img_07", mingzi: "孫策 (伯符)", name: "Sun Ce (Bofu)" },
  { img: "img_07", mingzi: "孫權 (仲謀)", name: "Sun Quan (Zhongmou)" },
  { img: "img_07", mingzi: "周瑜 (公瑾)", name: "Zhou Yu (Gongjin)" },
  { img: "img_07", mingzi: "魯肅 (子敬)", name: "Lu Su (Zijing)" },
  { img: "img_07", mingzi: "陸遜 (伯言)", name: "Lu Xun (Boyan)" },
  { img: "img_07", mingzi: "程普 (德謀)", name: "Cheng Pu (Demou)" },
  { img: "img_07", mingzi: "甘寧 (興霸)", name: "Gan Ning (Xingba)" },
  { img: "img_07", mingzi: "黃蓋 (公覆)", name: "Huang Gai (Gongfu)" },
  { img: "img_07", mingzi: "呂蒙 (子明)", name: "Lü Meng (Ziming)" },
  { img: "img_07", mingzi: "周泰 (幼平)", name: "Zhou Tai (Youping)" },
  { img: "img_07", mingzi: "韓當 (義公)", name: "Han Dang (Yigong)" },
  { img: "img_07", mingzi: "張昭 (子布)", name: "Zhang Zhao (Zibu)" },
  { img: "img_07", mingzi: "丁奉 (承淵)", name: "Ding Feng (Chengyuan)" },
  { img: "img_07", mingzi: "潘璋 (文珪)", name: "Pan Zhang (Wengui)" },
  { img: "img_07", mingzi: "孫桓 (叔武)", name: "Sun Huan (Shuwu)" },
  { img: "img_07", mingzi: "徐盛 (文嚮)", name: "Xu Sheng (Wenxiang)" },
  { img: "img_07", mingzi: "諸葛瑾 (子瑜)", name: "Zhuge Jin (Ziyu)" },
  { img: "img_07", mingzi: "吳夫人", name: "Lady Wu" },
  { img: "img_07", mingzi: "孫夫人", name: "Lady Sun" },
  { img: "img_07", mingzi: "大橋", name: "Da Qiao" },
  { img: "img_07", mingzi: "小橋", name: "Xiao Qiao" },
  { img: "img_07", mingzi: "陸績 (公紀)", name: "Lu Ji (Gongji)" },
  { img: "img_07", mingzi: "橋玄 (公祖)", name: "Qiao Xuan (Gongzu)" },
  { img: "img_07", mingzi: "薛綜 (敬文)", name: "Xue Zong (Jingwen)" },
  { img: "img_07", mingzi: "嚴畯 (曼才)", name: "Yan Jun (Mancai)" },
  { img: "img_07", mingzi: "虞翻 (仲翔)", name: "Yu Fan (Zhongxiang)" },
  { img: "img_07", mingzi: "朱然 (義封)", name: "Zhu Ran (Yifeng)" },
];

export const Other = [
  { img: "img_12", mingzi: "董卓 (仲穎)", name: "Dong Zhuo (Zhongying)" },
  { img: "img_12", mingzi: "呂布 (奉先)", name: "Lu Bu (Fengxian)" },
  { img: "img_12", mingzi: "貂蟬", name: "Diao Chan" },
  { img: "img_12", mingzi: "郭汜", name: "Guo Si" },
  { img: "img_12", mingzi: "華雄", name: "Hua Xiong" },
  { img: "img_12", mingzi: "李傕 (稚然)", name: "Li Jue (Zhiran)" },
  { img: "img_12", mingzi: "李儒 (文優)", name: "Li Ru (Wenyou)" },
  { img: "img_12", mingzi: "陳宮 (公臺)", name: "Chen Gong (Gongtai)" },
  { img: "img_12", mingzi: "公孫瓚 (伯珪)", name: "Gongsun Zan (Bogui)" },
  { img: "img_12", mingzi: "郭圖", name: "Guo Tu" },
  { img: "img_12", mingzi: "韓遂 (文約)", name: "Han Sui (Wenyue)" },
  { img: "img_12", mingzi: "華佗 (元化)", name: "Hua Tuo (Yuanhua)" },
  { img: "img_12", mingzi: "紀靈", name: "Ji Ling" },
  { img: "img_12", mingzi: "馬騰 (壽成)", name: "Ma Teng (Shoucheng)" },
  { img: "img_12", mingzi: "逄紀 (元圖)", name: "Pang Ji (Yuantu)" },
  { img: "img_12", mingzi: "司馬徽 (德操)", name: "Sima Hui (Decao)" },
  { img: "img_12", mingzi: "司馬炎 (安世)", name: "Sima Yan (Anshi)" },
  { img: "img_12", mingzi: "田豐 (元皓)", name: "Tian Feng (Yuanhao)" },
  { img: "img_12", mingzi: "文醜", name: "Wen Chou" },
  { img: "img_12", mingzi: "許攸 (子遠)", name: "Xu You (Ziyuan)" },
  { img: "img_12", mingzi: "張任", name: "Zhang Ren" },
  { img: "img_12", mingzi: "張溫 (伯慎)", name: "Zhang Wen (Boshen)" },
  { img: "img_12", mingzi: "袁紹 (本初)", name: "Yuan Shao (Benchu)" },
  { img: "img_12", mingzi: "袁譚 (顯思)", name: "Yuan Tan (Xiansi)" },
  { img: "img_12", mingzi: "袁熙 (顯奕)", name: "Yuan Xi (Xianyi)" },
  { img: "img_12", mingzi: "顔良", name: "Yan Liang" },
  { img: "img_12", mingzi: "袁尚 (顯甫)", name: "Yuan Shang (Xianfu)" },
  { img: "img_12", mingzi: "袁术 (公路)", name: "Yuan Shu (Gonglu)" },
  
];